spring:
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?characterEncoding=UTF-8
    password: root
    username: root
  mvc: #sswagger2.x与springboot2.6以上搭配报错解决
    pathmatch:
      matching-strategy: ant_path_matcher
  #设置thymeleaf 缓存
  thymeleaf:
    cache: false
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ding.entities

# log
logging:
  level:
    com.ding : debug

